version: '3'
services:
    cuckoo:
        build: .
        privileged: true
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
            - /dev/vboxdrv:/dev/vboxdrv
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - /tmp:/tmp
            - ${CUCKOO_DATA_DIR}/virtualbox:/root/.config/VirtualBox
            - ${CUCKOO_DATA_DIR}/vmcloak:/root/.vmcloak
            - ${CUCKOO_DATA_DIR}/cuckoo:/root/.cuckoo
            - ${CUCKOO_ISO_DIR}:/root/isos
            - ${CUCKOO_MALWARE_DIR}:/root/malware
            - ./conf:/root/conf
        ports:
            - "3389:3389"
            - "8000:8000"
        dns:
            - 1.1.1.1
            - 8.8.8.8
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - ${CUCKOO_DATA_DIR}/mongo:/data/db
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - ${CUCKOO_DATA_DIR}/elastic:/usr/share/elasticsearch/data
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - ${CUCKOO_DATA_DIR}/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=cuckoo
            - POSTGRES_PASSWORD=cuckoo
            - POSTGRES_DB=cuckoo
